---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: markeble
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432