default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: database
  pool: 5

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "notes_app_development" %>
test:
  <<: *default
  database: notes_app_test
production:
  primary: &primary_production
    <<: *default
    database: notes_app_production
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: notes_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: notes_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: notes_app_production_cable
    migrations_paths: db/cable_migrate
